//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegratedResourceManagementSystem.Marketing.Marketing_Admin {
    
    
    public partial class Default {
        
        /// <summary>
        /// main_admin_menu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IntegratedResourceManagementSystem.Marketing.Marketing_Admin.controls.AdminMenuMain main_admin_menu;
    }
}
